[target.x86_64-unknown-linux-gnu]
linker = "scripts/zig-cc.sh"
rustflags = ["-C", "link-arg=-target", "-C", "link-arg=x86_64-linux-gnu"]

[env]
ZIG_GLOBAL_CACHE_DIR = { value = "target/zig-cache", relative = true }
ZIG_LOCAL_CACHE_DIR = { value = "target/zig-local-cache", relative = true }
